# Generated by Django 6.0.3 on 2026-04-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="isVerified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.CharField(default="100L", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="matricNo",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
