# Generated by Django 6.0.6 on 2026-06-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_isverified_user_level_user_matricno'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='examination_number',
            field=models.CharField(blank=True, help_text='Examination registration number for result checking', max_length=30, null=True, unique=True),
        ),
    ]
