# Generated by Django 6.0.3 on 2026-04-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="treasurysetting",
            name="early_payment_discount",
            field=models.IntegerField(default=0),
        ),
    ]
