# Generated by Django 5.0.3 on 2026-04-22 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_treasurysetting_early_payment_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankdetail",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="treasurysetting",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("undergraduate", "Undergraduate"),
                            ("postgraduate", "Postgraduate"),
                        ],
                        default="undergraduate",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "duration_years",
                    models.IntegerField(
                        default=4, help_text="Program duration in years"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="portal.department",
                    ),
                ),
            ],
            options={
                "ordering": ["department", "level", "name"],
                "unique_together": {("department", "code")},
            },
        ),
        migrations.CreateModel(
            name="PostgradProgram",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_requirement",
                    models.TextField(
                        help_text="Minimum entry requirements (e.g., 2.2 degree classification)"
                    ),
                ),
                ("thesis_required", models.BooleanField(default=True)),
                (
                    "research_component_percent",
                    models.IntegerField(
                        default=40,
                        help_text="Percentage of coursework dedicated to research",
                    ),
                ),
                ("internship_required", models.BooleanField(default=False)),
                (
                    "postgrad",
                    models.OneToOneField(
                        limit_choices_to={"level": "postgraduate"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postgrad_details",
                        to="portal.program",
                    ),
                ),
                (
                    "related_undergrad",
                    models.ManyToManyField(
                        help_text="Undergraduate programs that can lead to this postgraduate degree",
                        limit_choices_to={"level": "undergraduate"},
                        related_name="postgrad_options",
                        to="portal.program",
                    ),
                ),
            ],
        ),
    ]
