# Generated by Django 6.0.3 on 2026-04-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="face_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="application",
            name="gender",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="application",
            name="jamb_reg_no",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="application",
            name="jamb_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="application",
            name="left_index_finger_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="application",
            name="lga",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="application",
            name="nok_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="application",
            name="nok_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="application",
            name="nok_relation",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="application",
            name="permanent_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="application",
            name="right_index_finger_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="application",
            name="state_of_origin",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="application",
            name="type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
