# Generated by Django 6.0.3 on 2026-04-06 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_application_date_of_birth_application_face_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.CharField(default="Harmattan", max_length=20),
        ),
        migrations.AddField(
            model_name="course",
            name="session",
            field=models.CharField(default="2024/2025", max_length=20),
        ),
        migrations.CreateModel(
            name="Clearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("uploaded", "Uploaded"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "affidavit_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "lga_origin_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "age_declaration_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
