# Generated by Django 5.0.3 on 2026-04-22 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_course_semester_course_session_clearance"),
        ("portal", "0003_alter_bankdetail_id_alter_department_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["department", "code"]},
        ),
        migrations.AlterModelOptions(
            name="registration",
            options={"ordering": ["-session", "-semester"]},
        ),
        migrations.AddField(
            model_name="application",
            name="application_level",
            field=models.CharField(
                choices=[
                    ("undergraduate", "Undergraduate"),
                    ("postgraduate", "Postgraduate"),
                ],
                default="undergraduate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.program",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="credit_hours",
            field=models.IntegerField(
                default=3, help_text="Credit hours for postgraduate courses"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_elective",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("undergraduate", "Undergraduate"),
                    ("postgraduate", "Postgraduate"),
                    ("both", "Both UG & PG"),
                ],
                default="undergraduate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="level",
            field=models.CharField(
                choices=[
                    ("undergraduate", "Undergraduate"),
                    ("postgraduate", "Postgraduate"),
                ],
                default="undergraduate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.program",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="total_units",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="registration",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="clearance",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("user", "semester", "session", "level")},
        ),
        migrations.CreateModel(
            name="PostgraduateApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cgpa",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cumulative GPA from undergraduate",
                        max_digits=3,
                    ),
                ),
                (
                    "degree_classification",
                    models.CharField(
                        help_text="e.g., First Class, Upper Second Class", max_length=50
                    ),
                ),
                ("research_interest", models.TextField()),
                ("letter_of_intent", models.URLField(blank=True, max_length=500)),
                ("face_url", models.URLField(blank=True, max_length=500)),
                ("left_index_finger_url", models.URLField(blank=True, max_length=500)),
                ("right_index_finger_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        limit_choices_to={"level": "postgraduate"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.program",
                    ),
                ),
                (
                    "undergrad_program",
                    models.ForeignKey(
                        limit_choices_to={"level": "undergraduate"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="postgrad_applicants",
                        to="portal.program",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postgrad_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
