# Generated by Django 6.0.3 on 2026-04-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="bvn",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="nin",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="purpose",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="repayment_period",
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name="loan",
            name="type",
            field=models.CharField(default="Student Loan", max_length=50),
        ),
    ]
