# Generated by Django 6.0.3 on 2026-04-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finances",
            "0002_loan_bvn_loan_nin_loan_purpose_loan_repayment_period_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
