# Generated by Django 6.0.3 on 2026-04-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0003_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[
                    ("acceptance", "Acceptance Fee"),
                    ("tuition", "Tuition Fee"),
                    ("hostel", "Hostel Fee"),
                    ("topup", "Top Up"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
